import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Sidebar from "@/components/Sidebar";
import Dashboard from "./dashboard/page";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">

        <aside className="h-screen absolute top-0 left-0">
          <Sidebar children={undefined} />
        </aside>
        <main>
          {children}
        </main>
        
        
      </body>
    </html>
  );
}
